/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/Sum.hpp>
#include <v1/commonapi/SumDBusStubAdapter.hpp>

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createSumDBusStubAdapter(
                   const CommonAPI::DBus::DBusAddress &_address,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< SumDBusStubAdapter<::v1::commonapi::SumStub>>(_address, _connection, std::dynamic_pointer_cast<::v1::commonapi::SumStub>(_stub));
}

void initializeSumDBusStubAdapter() {
    CommonAPI::DBus::Factory::get()->registerStubAdapterCreateMethod(
        Sum::getInterface(), &createSumDBusStubAdapter);
}

INITIALIZER(registerSumDBusStubAdapter) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeSumDBusStubAdapter);
}

} // namespace commonapi
} // namespace v1
