/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201801251438.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Sum_DBUS_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_Sum_DBUS_STUB_ADAPTER_HPP_

#include <v1/commonapi/SumStub.hpp>
#include "v1/commonapi/SumDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::SumStub, typename... _Stubs>
class SumDBusStubAdapterInternal
    : public virtual SumStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> SumDBusStubAdapterHelper;

    ~SumDBusStubAdapterInternal() {
        deactivateManagedInstances();
        SumDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return Sum::getInterface();
    }

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::commonapi::SumStub,
        CommonAPI::Version
        > getSumInterfaceVersionStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::commonapi::SumStub,
        std::tuple< int32_t, int32_t>,
        std::tuple< int32_t>,
        std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::IntegerDeployment>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > sumStubDispatcher;

    SumDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      SumDBusStubAdapterHelper(_address, _connection, false, _stub) {
        SumDBusStubAdapterHelper::addStubDispatcher({ "sum", "ii" }, &sumStubDispatcher);
        SumDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getSumInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"sum\">\n"
            "<arg name=\"_a\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_b\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"_c\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::commonapi::SumStub,
    CommonAPI::Version
    > SumDBusStubAdapterInternal<_Stub, _Stubs...>::getSumInterfaceVersionStubDispatcher(&SumStub::lockInterfaceVersionAttribute, &SumStub::getInterfaceVersion, "uu");


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::commonapi::SumStub,
    std::tuple< int32_t, int32_t>,
    std::tuple< int32_t>,
    std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::IntegerDeployment>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>

    > SumDBusStubAdapterInternal<_Stub, _Stubs...>::sumStubDispatcher(
    &SumStub::sum, "i",
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr), static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)));


template <typename _Stub = ::v1::commonapi::SumStub, typename... _Stubs>
class SumDBusStubAdapter
    : public SumDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< SumDBusStubAdapter<_Stub, _Stubs...>> {
public:
    SumDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          SumDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Sum_DBUS_STUB_ADAPTER_HPP_
