/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201805221014.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/SumStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace commonapi {

SumStubDefault::SumStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(Sum::getInterfaceVersion()) {
}

const CommonAPI::Version& SumStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

SumStubRemoteEvent* SumStubDefault::initStubAdapter(const std::shared_ptr< SumStubAdapter> &_adapter) {
    CommonAPI::Stub<SumStubAdapter, SumStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void SumStubDefault::sum(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _a, int32_t _b, sumReply_t _reply) {
    (void)_client;
    (void)_a;
    (void)_b;
    int32_t c = 0;
    _reply(c);
}




SumStubDefault::RemoteEventHandler::RemoteEventHandler(SumStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace commonapi
} // namespace v1
